baseURL: 'http://example.org/'
defaultContentLanguage: 'en'
title: "Robin's Blog"
theme: 'PaperMod'

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: true
enableEmoji: true

menu:
  main:
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30

outputs:
  home:
    - HTML
    - RSS
    - JSON # nécessaire pour la recherche

taxonomies:
  tag: tags
  category: categories

params:
  defaultTheme: auto

  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true
  ShowToc: true # afficher le sommaire
  ShowReadingTime: true 
  ShowPostNavLinks: true
  hideFooter: true
  comments: true
  hidemeta: false
  hideSummary: false

  homeInfoParams:
    Title: "Welcome to my blog"
    Content: |
      Hi! My name is Robin. 
      I've been a software developer professionally for over 10 years now.
      I'm a very curious felow and I love to share about my learnings.
      I will write mostly about web development and especially about C#/.NET.
      I hope that you will find interesting to follow me and my journey.

  socialIcons:
    - name: github
      url: "https://github.com/rchoffardet"
    - name: twitter
      url: "https://twitter.com/CaptainSpic"
    - name: linkedin
      url: "https://www.linkedin.com/in/robin-choffardet/"
    - name: Rss
      url: "index.xml"

  profileMode:
    enabled: false # needs to be explicitly set

  editPost:
      URL: "https://github.com/rchoffardet/blog/tree/main/content"
      Text: "Suggest modifications" # edit text
      appendFilePath: true # to append file path to Edit link

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content", "tags"]

  cover:
    hiddenInList: true
